apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-monitor
  name: prometheus-vault-monitor
spec:
  selector:
    matchLabels:
      app: vault-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-monitor
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: vault
        image:  "image_url"
        env:
          - name: CSI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CSI_SACC
            value: "default"
        envFrom:
        - configMapRef:
            name: "vault"
        volumeMounts:
        - mountPath: /etc/vault
          name: vault
        ports:
          - containerPort: 8080
      volumes:
      - name: vault
        secret :
            secretName: "vault"
            items:
            - key: "vault.pem"
              path: vault.pem
